#!/bin/csh

#  ejw, 24-sep-01


if ($1 == start) then

#    echo ""
#    echo "   alarm_browser disabled 1: sergey"
#    echo ""

# run on CLON_DAQ but display on clonpc's
##  ssh -n $CLON_DAQ "(setenv DISPLAY clonpc0:0.0; alarm_browser -a $2 -u alarm_browser) >>& $CLON_LOG/run_log/alarm_browser.log &" &

#works
#  alarm_browser -a $2 -u alarm_browser >>& $CLON_LOG/run_log/alarm_browser.log &

  alarm_browser -a $2 -u alarm_browser >>& $CLON_LOG/run_log/alarm_browser.log &





else if ($1 == stop) then

#    echo ""
#    echo "   alarm_browser disabled 2: sergey"
#    echo ""
  stop_ipc_proc -a $2 -i alarm_browser -n $CLON_DAQ -p AlarmBrowser >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
