#!/bin/tcsh -f
#
#  ctoftest_exit - stops all DAQ processes for CTOF testsetup
#
#  SP, 18-Jul-2006
#  SP, 07-Mar-2012  :  after implement daq_comp.tcl


if ($HOST != $CLON_TEST) then
  echo ""
  echo " You should be logged into $CLON_TEST."
  echo ""
  exit (1)
endif
echo ""


echo " Stop EB"
stop_proc -n $CLON_TEST -p coda_eb -match "ctoftest" -s 0

echo " Stop ER"
stop_proc -n $CLON_TEST -p coda_er -match "ctoftest" -s 0

echo " Stop RunControl"
stop_proc -n $CLON_TEST -p runcontrol -match "ctoftest" -s 0

echo " Stop rcServer"
stop_proc -n $CLON_TEST -p rcServer -match "ctoftest" -s 0

echo " Stop ET"
stop_proc -n $CLON_TEST -p et_start -match "ctoftest" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_ctoftest


echo ""
echo " Kill terminals:"

stop_proc -n $CLON_TEST -p xterm -match "ET_ctoftest" -s 0
echo "                 ET_ctoftest done"

stop_proc -n $CLON_TEST -p xterm -match "EB_ctoftest" -s 0
echo "                 EB_ctoftest done"

stop_proc -n $CLON_TEST -p xterm -match "ER_ctoftest" -s 0
echo "                 ER_ctoftest done"

stop_proc -n $CLON_TEST -p xterm -match "runcontrol_ctoftest" -s 0
echo "                 runcontrol_ctoftest done"

##stop_proc -n $CLON_TEST -p xterm -match "CRATE_ctoftest" -s 0
##echo "                 CRATE_ctoftest done"


echo ""
echo " ctoftest_exit done"
echo ""


exit
