#!/bin/tcsh -f
#
#  ctof1_exit - stops all DAQ processes for CTOF testsetup
#

set host_name  = "ctof1"

if ($HOST != "ctof1") then
  echo ""
  echo " You should be logged into ctof1"
  echo ""
  exit (1)
endif
echo ""

echo " Stop ROCs"
stop_proc -n $host_name -p coda_roc_gef -match "ctoftest" -s 0

echo " Stop EB"
stop_proc -n $host_name -p coda_ebc -match "ctoftest" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_erc -match "ctoftest" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "ctoftest" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "ctoftest" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "ctoftest" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_ctoftest


echo ""
echo " Kill terminals:"

stop_proc -n $host_name -p xterm -match "ET_ctoftest" -s 0
echo "                 ET_ctoftest done"

stop_proc -n $host_name -p xterm -match "EB_ctoftest" -s 0
echo "                 EB_ctoftest done"

stop_proc -n $host_name -p xterm -match "ER_ctoftest" -s 0
echo "                 ER_ctoftest done"

stop_proc -n $host_name -p xterm -match "runcontrol_ctoftest" -s 0
echo "                 runcontrol_ctoftest done"

stop_proc -n $host_name -p xterm -match "CRATE_ctoftest" -s 0
echo "                 CRATE_ctoftest done"


echo ""
echo " ctof1_exit done"
echo ""


exit
