#!/bin/tcsh -f
#
#  ctof1_start - starts DAQ for CTOF testsetup
#


if ($HOST != "ctof1") then
  echo ""
  echo " You should be logged into ctof1"
  echo ""
  exit (1)
endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_ctoftest"
set EB_t  = "-T EB_ctoftest"
set ER_t  = "-T ER_ctoftest"
set RC_t  = "-T runcontrol_ctoftest"
set XT1_t = "-T CRATE_ctoftest"

set ET   = daq_comp_nossh.tcl
set EB   = daq_comp_nossh.tcl
set ER   = daq_comp_nossh.tcl
set RC   = daq_comp_nossh.tcl
set XT   = daq_comp_nossh.tcl

set ET_comp  = 'et_start -n 1000 -s 50000 -f /tmp/et_sys_ctoftest'
set EB_comp  = 'coda_ebc -s ctoftest -o "EB66 CDEB" '
set ER_comp  = 'coda_erc -s ctoftest -o "ER66 ER" '
set RC_comp  = 'runcontrol -s ctoftest -cedit -dbedit'
set XT1_comp = 'coda_roc_gef -s ctoftest -o "ctof1 ROC" '


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`

echo " Start connection to CRATE_ctoftest"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`

echo ""
echo " ctof1_start done"
echo ""


exit
