#!/bin/csh -f
#
#  dcrb2_exit - stops all processes for DCRB2 DAQ
#
#  SP, 04-Mar-2012


set host_name  = "dcrb2"

if ($HOST != $host_name && $HOST != $host_name.jlab.org) then
  echo ""
  echo " You should be logged into $host_name"
  echo ""
  exit (1)
endif
echo ""


echo " Stop ROCs"
stop_proc -n $host_name -p coda_roc_gef -match "clasdcrb2" -s 0
stop_proc -n $host_name -p coda_roc -match "clasdcrb2" -s 0

echo " Stop EB"
stop_proc -n $host_name -p coda_ebc -match "clasdcrb2" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_erc -match "clasdcrb2" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "clasdcrb2" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "clasdcrb2" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "clasdcrb2" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clasdcrb2


echo ""
echo " Kill terminals:"

stop_proc -n $host_name -p xterm -match "ET_dcrb2" -s 0
echo "                 ET_dcrb2 done"

stop_proc -n $host_name -p xterm -match "EB_dcrb2" -s 0
echo "                 EB_dcrb2 done"

stop_proc -n $host_name -p xterm -match "ER_dcrb2" -s 0
echo "                 ER_dcrb2 done"

stop_proc -n $host_name -p xterm -match "runcontrol_dcrb2" -s 0
echo "                 runcontrol_dcrb2 done"

stop_proc -n $host_name -p xterm -match "CRATE_dcrb2" -s 0
echo "                 CRATE_dcrb2 done"

stop_proc -n $host_name -p xterm -match "CRATE_dcrb2gtp" -s 0
echo "                 CRATE_dcrb2gtp done"


echo ""
echo " dcrb2_exit done"
echo ""


exit
