#!/bin/csh -f
#
#  eelfcat1_exit - stops all processes for EEL room 109 testsetup
#
#  SP, 04-Mar-2012


set host_name  = "eelfcat1"

if ($HOST != "eelfcat1") then
  echo ""
  echo " You should be logged into $host_name"
  echo ""
  exit (1)
endif
echo ""


echo " Stop ROCs"
stop_proc -n $host_name -p coda_roc_gef -match "eelfcat1" -s 0

echo " Stop EB"
stop_proc -n $host_name -p coda_ebc -match "eelfcat1" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_erc -match "eelfcat1" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "eelfcat1" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "eelfcat1" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "eelfcat1" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_eelfcat1


echo ""
echo " Kill terminals:"
stop_proc -n $host_name -p xterm -match "ET_eelfcat1" -s 0

stop_proc -n $host_name -p xterm -match "EB_eelfcat1" -s 0

stop_proc -n $host_name -p xterm -match "ER_eelfcat1" -s 0

stop_proc -n $host_name -p xterm -match "runcontrol_eelfcat1" -s 0

stop_proc -n $host_name -p xterm -match "CRATE_eelfcat1" -s 0



echo ""
echo " eelfcat1_exit done"
echo ""


exit
