#!/bin/csh -f
#
#  fc_exit - stops all processes for forward carriage of the CLAS12
#

if ($HOST != "clondaq4" && $HOST != "clondaq4.jlab.org" ) then
  echo ""
  echo " You should be logged into clondaq4 machine"
  echo ""
  exit (1)
endif

#set host_name  = `echo $HOST | cut -c 1-8 `
#set nnn = `echo $HOST | cut -c 8-8 `
#set nn = 1$nnn

set host_name = `echo $HOST `
set nnn = 6
set nn = 1$nnn

echo ""
echo " Stop ROCs"
stop_proc -n adcecal$nnn -p coda_roc_gef -match "clasprod" -s 0
stop_proc -n adcpcal$nnn -p coda_roc_gef -match "clasprod" -s 0
stop_proc -n adcftof$nnn -p coda_roc_gef -match "clasprod" -s 0
stop_proc -n tdcecal$nnn -p coda_roc_gef -match "clasprod" -s 0
stop_proc -n tdcpcal$nnn -p coda_roc_gef -match "clasprod" -s 0
stop_proc -n tdcftof$nnn -p coda_roc_gef -match "clasprod" -s 0

echo ""
echo " Stop EB"
stop_proc -n $host_name -p coda_ebc -match "clasprod" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_erc -match "clasprod" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "clasprod" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "clasprod" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "clasprod" -s 0
#kill -9 `ps -ef | grep et_start | grep et_sys_clasprod | awk '{print $2}'`

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clasprod


set ET_t  = "ET_sector$nnn"
set EB_t  = "EB_sector$nnn"
set ER_t  = "ER_sector$nnn"
set RC_t  = "runcontrol_sector$nnn"
set XT1_t = "CRATE_sector$nnn"

echo ""
echo " Kill terminals:"
stop_proc -n $host_name -p xterm -match "$ET_t" -s 0
echo "                 ET_sector$nnn done"

stop_proc -n $host_name -p xterm -match "$EB_t" -s 0
echo "                 EB_sector$nnn done"

stop_proc -n $host_name -p xterm -match "$ER_t" -s 0
echo "                 ER_sector$nnn done"

stop_proc -n $host_name -p xterm -match "$RC_t" -s 0
echo "                 runcontrol_sector$nnn done"

stop_proc -n $host_name -p xterm -match "$XT1_t" -s 0
echo "                 CRATE_sector$nnn done"


echo ""
echo " sector_exit done"
echo ""


exit
