#!/bin/csh -f
#
#  hbtest_exit - stops all processes for hbtest testsetup
#
#  SP, 24-Feb-2012


if ( ($HOST != "highbtest3") && ($HOST != "highbtest3.jlab.org") ) then
  echo ""
  echo " You should be logged into highbtest3"
  echo ""
  exit (1)
endif

echo " Stop ROCs"


set aaa = `ssh -n highbtest3 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n highbtest3 kill -9 $aaa



echo " Stop EB"
stop_proc -n highbtest3 -p coda_ebc -match "clashbtest" -s 0

echo " Stop ER"
stop_proc -n highbtest3 -p coda_erc -match "clashbtest" -s 0

echo " Stop RunControl"
stop_proc -n highbtest3 -p runcontrol -match "clashbtest" -s 0

echo " Stop rcServer"
stop_proc -n highbtest3 -p rcServer -match "clashbtest" -s 0

echo " Stop ET"
stop_proc -n highbtest3 -p et_start -match "clashbtest" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clashbtest


echo ""
echo " Kill terminals:"
stop_proc -n highbtest3 -p xterm -match "ET_hbtest" -s 0
echo "                 ET_hbtest done"

stop_proc -n highbtest3 -p xterm -match "EB_hbtest" -s 0
echo "                 EB_hbtest done"

stop_proc -n highbtest3 -p xterm -match "ER_hbtest" -s 0
echo "                 ER_hbtest done"

stop_proc -n highbtest3 -p xterm -match "runcontrol_hbtest" -s 0
echo "                 runcontrol_hbtest done"

stop_proc -n highbtest3 -p xterm -match "CRATE_hbtest3" -s 0
echo "                 CRATE_hbtest3 done"



echo ""
echo " hbtest_exit done"
echo ""


exit
