#!/bin/csh -f
#
#  hps3_exit - stops all processes for HPS setup
#

if ( ($HOST != "clondaq3") && ($HOST != "clondaq3.jlab.org") ) then
  echo ""
  echo " You should be logged into clondaq3"
  echo ""
  exit (1)
endif

echo " Stop ROCs"


echo " Stop EB"
stop_proc -n clondaq3 -p coda_ebc -match "clashps" -s 0

echo " Stop ER"
stop_proc -n clondaq3 -p coda_erc -match "clashps" -s 0

echo " Stop RunControl"
stop_proc -n clondaq3 -p runcontrol -match "clashps" -s 0

echo " Stop rcServer"
stop_proc -n clondaq3 -p rcServer -match "clashps" -s 0

echo " Stop ET"
stop_proc -n clondaq3 -p et_start -match "clashps" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clashps


echo ""
echo " Kill terminals:"
stop_proc -n clondaq3 -p xterm -match "ET_hps" -s 0
echo "                 ET_hps done"

stop_proc -n clondaq3 -p xterm -match "EB_hps" -s 0
echo "                 EB_hps done"

stop_proc -n clondaq3 -p xterm -match "ER_hps" -s 0
echo "                 ER_hps done"

stop_proc -n clondaq3 -p xterm -match "runcontrol_hps" -s 0
echo "                 runcontrol_hps done"


echo ""
echo " hps3_exit done"
echo ""


exit
