#!/bin/tcsh -f
#
#  hps4_start - starts DAQ for HPS setup (Counting Room)
#

if ( ($HOST != "clondaq4") && ($HOST != "clondaq4.jlab.org") ) then
  echo ""
  echo " You should be logged into clondaq4"
  echo ""
  exit (1)
endif

set xinc  = 70
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"

set xpos  = 10
set ypos  = 0
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_hps"
set EB_t  = "-T EB_hps"
set ER_t  = "-T ER_hps"
set RC_t  = "-T runcontrol_hps"

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp.tcl

set ET_comp  = 'et_start -n 1000 -s 500000 -f /tmp/et_sys_clashps'
set EB_comp  = 'coda_ebc -s clashps -o "EB41 CDEB" '
set ER_comp  = 'coda_erc -s clashps -o "ER41 ER" '
set RC_comp  = 'runcontrol -s clashps -cedit -dbedit'


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`



echo ""
echo " hps4_start done"
echo ""


exit
