#!/bin/tcsh -f
#
#  hps_start - starts DAQ for HPS setup (Counting Room)
#

if ( ($HOST != "clondaq5") && ($HOST != "clondaq5.jlab.org") ) then
  echo ""
  echo " You should be logged into clondaq5"
  echo ""
  exit (1)
endif

set xinc  = 70
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"

set xpos  = 10
set ypos  = 0
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_hps"
set EB_t  = "-T EB_hps"
set ER_t  = "-T ER_hps"
set RC_t  = "-T runcontrol_hps"
#set XT1_t = "-T CRATE_hps10"
#set XT2_t = "-T CRATE_dtm0"
#set XT3_t = "-T CRATE_dtm1"
#set XT4_t = "-T CRATE_dpm0"
#set XT5_t = "-T CRATE_dpm1"
#set XT6_t = "-T CRATE_dpm2"
#set XT7_t = "-T CRATE_dpm3"
#set XT8_t = "-T CRATE_dpm4"
#set XT9_t = "-T CRATE_dpm5"
#set XT10_t = "-T CRATE_dpm6"
#set XT11_t = "-T CRATE_dpm7"
#set XT12_t = "-T CRATE_dpm8"
#set XT13_t = "-T CRATE_dpm9"
#set XT14_t = "-T CRATE_dpm10"
#set XT15_t = "-T CRATE_dpm11"
#set XT16_t = "-T CRATE_dpm12"
#set XT17_t = "-T CRATE_dpm13"
#set XT18_t = "-T CRATE_dpm14"

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp.tcl

set ET_comp  = 'et_start -n 1000 -s 500000 -f /tmp/et_sys_clashps'
set EB_comp  = 'coda_ebc -s clashps -o "EB20 CDEB" '
set ER_comp  = 'coda_erc -s clashps -o "ER20 ER" '
set RC_comp  = 'runcontrol -s clashps -cedit -dbedit'
#set XT1_comp  = 'coda_roc_gef -s clashps -o "hps10 TS" '
#set XT2_comp  = 'coda_roc -s clashps -o "dtm0 ROC" '
#set XT3_comp  = 'coda_roc -s clashps -o "dtm1 ROC" '
#set XT4_comp  = 'coda_roc -s clashps -o "dpm0 ROC" '
#set XT5_comp  = 'coda_roc -s clashps -o "dpm1 ROC" '
#set XT6_comp  = 'coda_roc -s clashps -o "dpm2 ROC" '
#set XT7_comp  = 'coda_roc -s clashps -o "dpm3 ROC" '
#set XT8_comp  = 'coda_roc -s clashps -o "dpm4 ROC" '
#set XT9_comp  = 'coda_roc -s clashps -o "dpm5 ROC" '
#set XT10_comp  = 'coda_roc -s clashps -o "dpm6 ROC" '
#set XT11_comp  = 'coda_roc -s clashps -o "dpm7 ROC" '
#set XT12_comp  = 'coda_roc -s clashps -o "dpm8 ROC" '
#set XT13_comp  = 'coda_roc -s clashps -o "dpm9 ROC" '
#set XT14_comp  = 'coda_roc -s clashps -o "dpm10 ROC" '
#set XT15_comp  = 'coda_roc -s clashps -o "dpm11 ROC" '
#set XT16_comp  = 'coda_roc -s clashps -o "dpm12 ROC" '
#set XT17_comp  = 'coda_roc -s clashps -o "dpm13 ROC" '
#set XT18_comp  = 'coda_roc -s clashps -o "dpm14 ROC" '


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`

#echo " Start connection to CRATE_hps10"
#set ypos  = `expr $ypos + $yinc`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`

#echo " Start connection to CRATE_dtm0"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT2_t $color $geom$ypos -e $XT $XT2_comp >& /dev/null &`

#echo " Start connection to CRATE_dtm1"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT3_t $color $geom$ypos -e $XT $XT3_comp >& /dev/null &`


set xpos  = 500


#echo " Start connection to CRATE_dpm0"
#set ypos  = 0
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT4_t $color $geom$ypos -e $XT $XT4_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm1"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT5_t $color $geom$ypos -e $XT $XT5_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm2"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT6_t $color $geom$ypos -e $XT $XT6_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm3"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT7_t $color $geom$ypos -e $XT $XT7_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm4"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT8_t $color $geom$ypos -e $XT $XT8_comp >& /dev/null &`


set xpos  = 1000


#echo " Start connection to CRATE_dpm5"
#set ypos  = 0
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT9_t $color $geom$ypos -e $XT $XT9_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm6"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT10_t $color $geom$ypos -e $XT $XT10_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm7"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT11_t $color $geom$ypos -e $XT $XT11_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm8"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT12_t $color $geom$ypos -e $XT $XT12_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm9"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT13_t $color $geom$ypos -e $XT $XT13_comp >& /dev/null &`


set xpos  = 1500


#echo " Start connection to CRATE_dpm10"
#set ypos  = 0
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT14_t $color $geom$ypos -e $XT $XT14_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm11"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT15_t $color $geom$ypos -e $XT $XT15_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm12"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT16_t $color $geom$ypos -e $XT $XT16_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm13"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT17_t $color $geom$ypos -e $XT $XT17_comp >& /dev/null &`

#echo " Start connection to CRATE_dpm14"
#set ypos  = `expr $ypos + $yinc + 60`
#set geom  = "-geometry 70x12+$xpos+"
#set color = "-sb -sl 5000 -bg lightgreen -fg black"
#set tmp   = `xterm $XT18_t $color $geom$ypos -e $XT $XT18_comp >& /dev/null &`



echo ""
echo " hps_start done"
echo ""


exit
