#!/bin/csh -f
#
#  hps_exit - stops all processes for HPS testsetup on clon00
#
#  SP, 24-Feb-2012


if ( ($HOST != "hps1") && ($HOST != "hps1.jlab.org") ) then
  echo ""
  echo " You should be logged into hps1"
  echo ""
  exit (1)
endif

echo " Stop ROCs"

set aaa = `ssh -n hps2 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n hps2 kill -9 $aaa

set aaa = `ssh -n hps1gtp ps -ef | grep coda_roc | awk '{print $1}'`
ssh -n hps1gtp kill -9 $aaa

set aaa = `ssh -n hps2gtp ps -ef | grep coda_roc | awk '{print $1}'`
ssh -n hps2gtp kill -9 $aaa

set aaa = `ssh -n hps1 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n hps1 kill -9 $aaa

set aaa = `ssh -n hps1 ps -ef | grep DiagGuiServer | awk '{print $2}'`
ssh -n hps1 kill -9 $aaa

set aaa = `ssh -n hps2 ps -ef | grep DiagGuiServer | awk '{print $2}'`
ssh -n hps1 kill -9 $aaa

###stop_proc -n hpstracker1 -p coda_roc_gef -match "clashps" -s 0
##stop_proc -n hps2 -p coda_roc_gef -match "clashps" -s 0
##stop_proc -n hps1gtp -p coda_roc -match "clashps" -s 0
##stop_proc -n hps2gtp -p coda_roc -match "clashps" -s 0
##stop_proc -n hps1 -p coda_roc_gef -match "clashps" -s 0


echo " Stop EB"
stop_proc -n hps1 -p coda_ebc -match "clashps" -s 0

echo " Stop ER"
stop_proc -n hps1 -p coda_erc -match "clashps" -s 0

echo " Stop RunControl"
stop_proc -n hps1 -p runcontrol -match "clashps" -s 0

echo " Stop rcServer"
stop_proc -n hps1 -p rcServer -match "clashps" -s 0

echo " Stop ET"
stop_proc -n hps1 -p et_start -match "clashps" -s 0
#kill -9 `ps -ef | grep et_start | grep et_sys_clashps | awk '{print $2}'`

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clashps


echo ""
echo " Kill terminals:"
stop_proc -n hps1 -p xterm -match "ET_hps" -s 0
echo "                 ET_hps done"

stop_proc -n hps1 -p xterm -match "EB_hps" -s 0
echo "                 EB_hps done"

stop_proc -n hps1 -p xterm -match "ER_hps" -s 0
echo "                 ER_hps done"

stop_proc -n hps1 -p xterm -match "runcontrol_hps" -s 0
echo "                 runcontrol_hps done"

stop_proc -n hps1 -p xterm -match "CRATE_hps1" -s 0
echo "                 CRATE_hps1 done"

stop_proc -n hps1 -p xterm -match "CRATE_hps2" -s 0
echo "                 CRATE_hps2 done"

stop_proc -n hps1 -p xterm -match "CRATE_hps1server" -s 0
echo "                 CRATE_hps1 done"

stop_proc -n hps1 -p xterm -match "CRATE_hps2server" -s 0
echo "                 CRATE_hps2 done"



echo ""
echo " hps_exit done"
echo ""


exit
