#!/bin/csh -f
#
#  hpsdaq3_exit - stops all processes for HPS testsetup on clon00
#

if ( ($HOST != "clondaq3") && ($HOST != "clondaq3.jlab.org") ) then
  echo ""
  echo " You should be logged into clondaq3"
  echo ""
  exit (1)
endif

echo " Stop ROCs"

set aaa = `ssh -n hps10 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n hps10 kill -9 $aaa

set aaa = `ssh -n dtm0 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dtm0 kill -9 $aaa

set aaa = `ssh -n dtm1 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dtm1 kill -9 $aaa

set aaa = `ssh -n dpm0 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm0 kill -9 $aaa

set aaa = `ssh -n dpm1 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm1 kill -9 $aaa

set aaa = `ssh -n dpm2 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm2 kill -9 $aaa

set aaa = `ssh -n dpm3 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm3 kill -9 $aaa

set aaa = `ssh -n dpm4 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm4 kill -9 $aaa

set aaa = `ssh -n dpm5 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm5 kill -9 $aaa

set aaa = `ssh -n dpm6 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm6 kill -9 $aaa

set aaa = `ssh -n dpm7 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm7 kill -9 $aaa

set aaa = `ssh -n dpm8 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm8 kill -9 $aaa

set aaa = `ssh -n dpm9 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm9 kill -9 $aaa

set aaa = `ssh -n dpm10 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm10 kill -9 $aaa

set aaa = `ssh -n dpm11 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm11 kill -9 $aaa

set aaa = `ssh -n dpm12 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm12 kill -9 $aaa

set aaa = `ssh -n dpm13 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm13 kill -9 $aaa

set aaa = `ssh -n dpm14 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n dpm14 kill -9 $aaa



echo " Stop EB"
stop_proc -n clondaq3 -p coda_ebc -match "clashps1" -s 0

echo " Stop ER"
stop_proc -n clondaq3 -p coda_erc -match "clashps1" -s 0

echo " Stop RunControl"
stop_proc -n clondaq3 -p runcontrol -match "clashps1" -s 0

echo " Stop rcServer"
stop_proc -n clondaq3 -p rcServer -match "clashps1" -s 0

echo " Stop ET"
stop_proc -n clondaq3 -p et_start -match "clashps1" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clashps1


echo ""
echo " Kill terminals:"
stop_proc -n clondaq3 -p xterm -match "ET_hps" -s 0
echo "                 ET_hps done"

stop_proc -n clondaq3 -p xterm -match "EB_hps" -s 0
echo "                 EB_hps done"

stop_proc -n clondaq3 -p xterm -match "ER_hps" -s 0
echo "                 ER_hps done"

stop_proc -n clondaq3 -p xterm -match "runcontrol_hps" -s 0
echo "                 runcontrol_hps done"

stop_proc -n clondaq3 -p xterm -match "CRATE_hps10" -s 0
echo "                 CRATE_hps10 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dtm0" -s 0
echo "                 CRATE_dtm0 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dtm1" -s 0
echo "                 CRATE_dtm1 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm0" -s 0
echo "                 CRATE_dpm0 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm1" -s 0
echo "                 CRATE_dpm1 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm2" -s 0
echo "                 CRATE_dpm2 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm3" -s 0
echo "                 CRATE_dpm3 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm4" -s 0
echo "                 CRATE_dpm4 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm5" -s 0
echo "                 CRATE_dpm5 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm6" -s 0
echo "                 CRATE_dpm6 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm7" -s 0
echo "                 CRATE_dpm7 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm8" -s 0
echo "                 CRATE_dpm8 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm9" -s 0
echo "                 CRATE_dpm9 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm10" -s 0
echo "                 CRATE_dpm10 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm11" -s 0
echo "                 CRATE_dpm11 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm12" -s 0
echo "                 CRATE_dpm12 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm13" -s 0
echo "                 CRATE_dpm13 done"

stop_proc -n clondaq3 -p xterm -match "CRATE_dpm14" -s 0
echo "                 CRATE_dpm14 done"


echo ""
echo " hpsdaq3_exit done"
echo ""


exit
