#!/bin/tcsh -f
#
#  mvt1_exit - stops all DAQ processes for MVT testsetup
#

set host_name  = "mvt1"

if ($HOST != "mvt1") then
  echo ""
  echo " You should be logged into mvt1"
  echo ""
  exit (1)
endif
echo ""

echo " Stop ROCs"
stop_proc -n $host_name -p coda_roc_gef -match "mvttest" -s 0

echo " Stop EB"
stop_proc -n $host_name -p coda_ebc -match "mvttest" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_erc -match "mvttest" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "mvttest" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "mvttest" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "mvttest" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_mvttest


echo ""
echo " Kill terminals:"

stop_proc -n $host_name -p xterm -match "ET_mvttest" -s 0
echo "                 ET_mvttest done"

stop_proc -n $host_name -p xterm -match "EB_mvttest" -s 0
echo "                 EB_mvttest done"

stop_proc -n $host_name -p xterm -match "ER_mvttest" -s 0
echo "                 ER_mvttest done"

stop_proc -n $host_name -p xterm -match "runcontrol_mvttest" -s 0
echo "                 runcontrol_mvttest done"

stop_proc -n $host_name -p xterm -match "CRATE_mvttest" -s 0
echo "                 CRATE_mvttest done"


echo ""
echo " mvt1_exit done"
echo ""


exit
