#!/bin/csh -f
#
# roc_xterms_exit - kill ROC Xterms in the current workspace
#

set name = hps11
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = hps1
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = hps2
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = hps12
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = hps1gtp
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = hps2gtp
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dtm0
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dtm1
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm0
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm1
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm2
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm3
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm4
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm5
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm6
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm7
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm8
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm9
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm10
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm11
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm12
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm13
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

set name = dpm14
set aaa = `ssh -n $name ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n $name kill -9 $aaa
set a = `ps -ef | grep xterm | grep $name | awk '{print $2}'`
kill -9 $a

exit




