#!/bin/tcsh -f
#
#  sector_start - starts DAQ for one sector of the CLAS12
#

set nnn = `echo $HOST | cut -c 8-8 `
set nn = 1$nnn

if ($HOST != "adcecal1" && $HOST != "adcecal1.jlab.org" && \
    $HOST != "adcecal2" && $HOST != "adcecal2.jlab.org" && \
    $HOST != "adcecal3" && $HOST != "adcecal3.jlab.org" && \
    $HOST != "adcecal4" && $HOST != "adcecal4.jlab.org" && \
    $HOST != "adcecal5" && $HOST != "adcecal5.jlab.org" && \
    $HOST != "adcecal6" && $HOST != "adcecal6.jlab.org" ) then
  echo ""
  echo " You should be logged into adcecal1[2,3,4,5,6] machine"
  echo ""
  exit (1)
endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_sector$nnn"
set EB_t  = "-T EB_sector$nnn"
set ER_t  = "-T ER_sector$nnn"
set RC_t  = "-T runcontrol_sector$nnn"
set XT1_t = "-T adcecal1_CRATE_sector$nnn"
set XT2_t = "-T adcpcal1_CRATE_sector$nnn"
set XT3_t = "-T adcftof1_CRATE_sector$nnn"
set XT4_t = "-T tdcecal1_CRATE_sector$nnn"
set XT5_t = "-T tdcpcal1_CRATE_sector$nnn"
set XT6_t = "-T tdcftof1_CRATE_sector$nnn"

set ET   = daq_comp_nossh.tcl
set EB   = daq_comp_nossh.tcl
set ER   = daq_comp_nossh.tcl
set RC   = daq_comp_nossh.tcl
##set XT   = daq_comp_nossh.tcl
set XT   = daq_comp.tcl

set ET_comp   = "et_start -n 1000 -s 200000 -f /tmp/et_sys_clasprod$nnn"
set EB_comp   = "coda_ebc -s clasprod$nnn -o 'EB$nn CDEB' "
set ER_comp   = "coda_erc -s clasprod$nnn -o 'ER$nn ER' "
set RC_comp   = "runcontrol -s clasprod$nnn -cedit -dbedit"




set XT_comp0 = 'coda_roc_gef -s clasprod'

set XT1_comp1 = ' -o "adcecal'
set XT1_comp2 = ' TS" '
set XT1_comp  = "$XT_comp0$nnn$XT1_comp1$nnn$XT1_comp2"

set XT2_comp1 = ' -o "adcpcal'
set XT2_comp2 = ' ROC" '
set XT2_comp  = "$XT_comp0$nnn$XT2_comp1$nnn$XT2_comp2"

set XT3_comp1 = ' -o "adcftof'
set XT3_comp2 = ' ROC" '
set XT3_comp  = "$XT_comp0$nnn$XT3_comp1$nnn$XT3_comp2"

set XT4_comp1 = ' -o "tdcecal'
set XT4_comp2 = ' ROC" '
set XT4_comp  = "$XT_comp0$nnn$XT4_comp1$nnn$XT4_comp2"

set XT5_comp1 = ' -o "tdcpcal'
set XT5_comp2 = ' ROC" '
set XT5_comp  = "$XT_comp0$nnn$XT5_comp1$nnn$XT5_comp2"

set XT6_comp1 = ' -o "tdcftof'
set XT6_comp2 = ' ROC" '
set XT6_comp  = "$XT_comp0$nnn$XT6_comp1$nnn$XT6_comp2"





echo "$XT2_comp"

echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`




echo " Start connection to CRATE_sector$nnn"
set roc   = "sector$nnn"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`

echo " Start connection to CRATE_sector$nnn"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT2_t $color $geom$ypos -e $XT $XT2_comp >& /dev/null &`

echo " Start connection to CRATE_sector$nnn"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT3_t $color $geom$ypos -e $XT $XT3_comp >& /dev/null &`

echo " Start connection to CRATE_sector$nnn"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT4_t $color $geom$ypos -e $XT $XT4_comp >& /dev/null &`

echo " Start connection to CRATE_sector$nnn"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT5_t $color $geom$ypos -e $XT $XT5_comp >& /dev/null &`

echo " Start connection to CRATE_sector$nnn"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT6_t $color $geom$ypos -e $XT $XT6_comp >& /dev/null &`

echo ""
echo " sector_start done"
echo ""


exit
