#!/bin/csh -f
#
#  svtsystem1_exit - stops all processes for SVT testsetup
#


if ( ($HOST != "svtsystem1") && ($HOST != "svtsystem1.jlab.org") ) then
  echo ""
  echo " You should be logged into svtsystem1"
  echo ""
  exit (1)
endif

echo " Stop ROCs"

set aaa = `ssh -n svt2 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n svt2 kill -9 $aaa

set aaa = `ssh -n svt5 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n svt5 kill -9 $aaa

set aaa = `ssh -n svt7 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n svt7 kill -9 $aaa




echo " Stop EB"
stop_proc -n svtsystem1 -p coda_ebc -match "classvt" -s 0

echo " Stop ER"
stop_proc -n svtsystem1 -p coda_erc -match "classvt" -s 0

echo " Stop RunControl"
stop_proc -n svtsystem1 -p runcontrol -match "classvt" -s 0

echo " Stop rcServer"
stop_proc -n svtsystem1 -p rcServer -match "classvt" -s 0

echo " Stop ET"
stop_proc -n svtsystem1 -p et_start -match "classvt" -s 0
#kill -9 `ps -ef | grep et_start | grep et_sys_classvt | awk '{print $2}'`

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_classvt


echo ""
echo " Kill terminals:"
stop_proc -n svtsystem1 -p xterm -match "ET_svt" -s 0
echo "                 ET_svt done"

stop_proc -n svtsystem1 -p xterm -match "EB_svt" -s 0
echo "                 EB_svt done"

stop_proc -n svtsystem1 -p xterm -match "ER_svt" -s 0
echo "                 ER_svt done"

stop_proc -n svtsystem1 -p xterm -match "runcontrol_svt" -s 0
echo "                 runcontrol_svt done"

stop_proc -n svtsystem1 -p xterm -match "CRATE_svt2" -s 0
echo "                 CRATE_svt2 done"

stop_proc -n svtsystem1 -p xterm -match "CRATE_svt5" -s 0
echo "                 CRATE_svt5 done"

stop_proc -n svtsystem1 -p xterm -match "CRATE_svt7" -s 0
echo "                 CRATE_svt7 done"



echo ""
echo " svtsystem1_exit done"
echo ""


exit
