#!/bin/tcsh -f
#
#  svtsystem1_start - starts DAQ for HPS testsetup (Counting Room)
#


if ( ($HOST != "svtsystem1") && ($HOST != "svtsystem1.jlab.org") ) then
  echo ""
  echo " You should be logged into svtsystem1"
  echo ""
  exit (1)
endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_svt"
set EB_t  = "-T EB_svt"
set ER_t  = "-T ER_svt"
set RC_t  = "-T runcontrol_svt"
set XT1_t = "-T CRATE_svt2"
set XT2_t = "-T CRATE_svt5"
set XT3_t = "-T CRATE_svt7"

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp.tcl

set ET_comp  = 'et_start -n 5000 -s 200000 -f /tmp/et_sys_classvt'
set EB_comp  = 'coda_ebc -s classvt -o "EB2 CDEB" '
set ER_comp  = 'coda_erc -s classvt -o "ER2 ER" '
set RC_comp  = 'runcontrol -s classvt -cedit -dbedit'
set XT1_comp  = 'coda_roc_gef -s classvt -o "svt2 TS" '
set XT2_comp  = 'coda_roc_gef -s classvt -o "svt5 ROC" '
set XT3_comp  = 'coda_roc_gef -s classvt -o "svt7 ROC" '


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`

echo " Start connection to CRATE_svt2"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`

echo " Start connection to CRATE_svt5"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT2_t $color $geom$ypos -e $XT $XT2_comp >& /dev/null &`

echo " Start connection to CRATE_svt7"
set ypos  = `expr $ypos + $yinc + 60`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT3_t $color $geom$ypos -e $XT $XT3_comp >& /dev/null &`



echo ""
echo " svtsystem1_start done"
echo ""


exit
