#!/bin/tcsh -f
#
#  testsetup_start - starts all processes on CLON_TEST
#


if ($HOST != $CLON_TEST) then
  echo ""
  echo " You should be logged into $CLON_TEST."
  echo ""
  exit (1)
endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t   = "-T ET_testsetup"
set EB_t   = "-T EB_testsetup"
set ER_t   = "-T ER_testsetup"
set RC_t   = "-T runcontrol_testsetup"
set XT1_t  = "-T croctest1_testsetup"
set XT2_t  = "-T croctest2_testsetup"
set XT10_t = "-T croctest10_testsetup"

#set ET   = testsetup_et.tcl
#set EB   = testsetup_eb.tcl
#set ER   = testsetup_er.tcl
#set RC   = testsetup_rc.tcl
#set XT   = testsetup_prxt.tcl

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp.tcl

set ET_comp  = 'et_start -n 1000 -s 100000 -f /tmp/et_sys_clastest'
set EB_comp  = 'coda_eb -s clastest -o "EB5 CDEB" -i'
set ER_comp  = 'coda_er -s clastest -o "ER5 ER" -i'
set RC_comp  = 'runcontrol -s clastest -cedit -dbedit'
set XT_comp  = 'tsconnect '


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`


echo " Start serial connection to croctest1"
set roc   = "croctest1"
set ypos  = `expr $ypos + $yinc`
set color = "-sb -sl 5000"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT_comp $roc >& /dev/null &`

#echo " Start serial connection to croctest2"
#set roc   = "croctest2"
#set ypos  = `expr $ypos + $yinc`
#set color = "-sb -sl 5000"
#set tmp   = `xterm $XT2_t $color $geom$ypos -e $XT $XT_comp $roc >& /dev/null &`

echo " Start serial connection to croctest10"
set roc   = "croctest10"
set ypos  = `expr $ypos + $yinc`
#set geom  = "-geometry 70x9+$xpos+"
set color = "-sb -sl 5000"
set tmp   = `xterm $XT10_t $color $geom$ypos -e $XT $XT_comp $roc >& /dev/null &`


echo ""
echo " testsetup_start done"
echo ""


exit
