#!/bin/tcsh -f
#
#  wolfram_start - starts DAQ for TEDF testsetup 
#
#  SP, 17-Sep-2007
#  SP, 26-Jun-2012  :  implement daq_comp.tcl


if ($HOST != "clon00") then
  echo ""
  echo " You should be logged into clon00"
  echo ""
  exit (1)
endif

set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_wolfram"
set EB_t  = "-T EB_wolfram"
set ER_t  = "-T ER_wolfram"
set RC_t  = "-T runcontrol_wolfram"
set XT1_t = "-T VME_wolfram1"

#set ET   = wolfram_et.tcl
#set EB   = wolfram_eb.tcl
#set ER   = wolfram_er.tcl
#set RC   = wolfram_rc.tcl
#set XT   = wolfram_prxt.tcl

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp.tcl

set ET_comp  = 'et_start -n 1000 -s 100000 -f /tmp/et_sys_claswolf'
set EB_comp  = 'coda_eb -s claswolf -o "EB2 CDEB" -i'
set ER_comp  = 'coda_er -s claswolf -o "ER2 ER" -i'
set RC_comp  = 'runcontrol -s claswolf -cedit -dbedit'
set XT_comp  = 'tsconnect '


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`


echo " Start serial connection to VME_wolfram"
set roc   = "wolfram1"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT_comp $roc >& /dev/null &`


echo ""
echo " wolfram_start done"
echo ""


exit
