#!/bin/csh -f
#
#  wolfram_exit - stops all DAQ processes
#
#  SP, 17-Sep-2007
#  SP, 26-Jun-2012  :  after implement daq_comp.tcl


set host_name  = "clon00"

if ($HOST != "clon00") then
  echo ""
  echo " You should be logged into $host_name"
  echo ""
  exit (1)
endif
echo ""


echo " Stop EB"
stop_proc -n $host_name -p coda_eb -match "claswolf" -s 0

echo " Stop ER"
stop_proc -n $host_name -p coda_er -match "claswolf" -s 0

echo " Stop RunControl"
stop_proc -n $host_name -p runcontrol -match "claswolf" -s 0

echo " Stop rcServer"
stop_proc -n $host_name -p rcServer -match "claswolf" -s 0

echo " Stop ET"
stop_proc -n $host_name -p et_start -match "claswolf" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_claswolf


echo ""
echo " Kill terminals:"
stop_proc -n $host_name -p xterm -match "ET_wolfram" -s 0
echo "                 ET_wolfram done"

stop_proc -n $host_name -p xterm -match "EB_wolfram" -s 0
echo "                 EB_wolfram done"

stop_proc -n $host_name -p xterm -match "ER_wolfram" -s 0
echo "                 ER_wolfram done"

stop_proc -n $host_name -p xterm -match "runcontrol_wolfram" -s 0
echo "                 runcontrol_wolfram done"

stop_proc -n $host_name -p xterm -match "VME_wolfram1" -s 0
echo "                 VME_wolfram1 done"


echo ""
echo " wolfram_exit done"
echo ""


exit
