#!/bin/csh -f
#
#  zedboard_exit - stops all processes for zedboard
#
#  SP, 24-Feb-2012


echo " Stop ROCs"


set aaa = `ssh -n zedboard1 ps -ef | grep coda_roc | awk '{print $2}'`
ssh -n zedboard1 kill -9 $aaa


echo " Stop EB"
stop_proc -n clonpc0 -p coda_ebc -match "clastest0" -s 0

echo " Stop ER"
stop_proc -n clonpc0 -p coda_erc -match "clastest0" -s 0

echo " Stop RunControl"
stop_proc -n clonpc0 -p runcontrol -match "clastest0" -s 0

echo " Stop rcServer"
stop_proc -n clonpc0 -p rcServer -match "clastest0" -s 0

echo " Stop ET"
stop_proc -n clonpc0 -p et_start -match "clastest0" -s 0

echo " Remove ET system file"
sleep 3
rm -f /tmp/et_sys_clastest0


echo ""
echo " Kill terminals:"
stop_proc -n clonpc0 -p xterm -match "ET_zedboard" -s 0
echo "                 ET_zedboard done"

stop_proc -n clonpc0 -p xterm -match "EB_zedboard" -s 0
echo "                 EB_zedboard done"

stop_proc -n clonpc0 -p xterm -match "ER_zedboard" -s 0
echo "                 ER_zedboard done"

stop_proc -n clonpc0 -p xterm -match "runcontrol_zedboard" -s 0
echo "                 runcontrol_zedboard done"

stop_proc -n clonpc0 -p xterm -match "CRATE_zedboard1" -s 0
echo "                 CRATE_zedboard1 done"


echo ""
echo " zedboard_exit done"
echo ""


exit
