#!/bin/tcsh -f
#
#  zedboard_start - starts DAQ for zedboard
#
#  SP, 24-Feb-2012
#  SP, 01-Mar-2012  :  implement daq_comp.tcl


set xpos  = 700
set ypos  = 0
set yinc  = 145
set lines = 7
set color = "-bg blue -fg white -sb -sl 5000"
set geom  = "-geometry 70x$lines+$xpos+"

set ET_t  = "-T ET_zedboard"
set EB_t  = "-T EB_zedboard"
set ER_t  = "-T ER_zedboard"
set RC_t  = "-T runcontrol_zedboard"
set XT1_t = "-T CRATE_zedboard1"

set ET   = daq_comp.tcl
set EB   = daq_comp.tcl
set ER   = daq_comp.tcl
set RC   = daq_comp.tcl
set XT   = daq_comp.tcl

set ET_comp  = 'et_start -n 2000 -s 500000 -f /tmp/et_sys_clastest0'
set EB_comp  = 'coda_ebc -s clastest0 -o "EB0 CDEB" -i'
set ER_comp  = 'coda_erc -s clastest0 -o "ER0 ER" -i'
set RC_comp  = 'runcontrol -s clastest0 -cedit -dbedit'
set XT1_comp  = 'coda_roc -s clastest0 -o "zedboard1 ROC" '


echo ""
echo " Start ET"
set tmp   = `xterm $ET_t $color $geom$ypos -e $ET $ET_comp >& /dev/null &`

echo " Start EB"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $EB_t $color $geom$ypos -e $EB $EB_comp >& /dev/null &`

echo " Start ER"
set ypos  = `expr $ypos + $yinc`
set tmp   = `xterm $ER_t $color $geom$ypos -e $ER $ER_comp >& /dev/null &`

echo " Start RunControl"
set ypos  = `expr $ypos + $yinc`
set color = "-bg yellow -fg black -sb -sl 5000"
set tmp   = `xterm $RC_t $color $geom$ypos -e $RC $RC_comp >& /dev/null &`

echo " Start connection to CRATE_zedboard1"
set ypos  = `expr $ypos + $yinc`
set geom  = "-geometry 70x12+$xpos+"
set color = "-sb -sl 5000 -bg lightgreen -fg black"
set tmp   = `xterm $XT1_t $color $geom$ypos -e $XT $XT1_comp >& /dev/null &`


echo ""
echo " zedboard_start done"
echo ""


exit
