#
# Makefile for coda/src/rc/ directory
#

all:
	  cd cg;                          gmake
	- cd sace3.1;                     gmake
	- cd motif;                       gmake
	- cd runControl/rcServer;         gmake
	- cd runControl/rcServer;         gmake install
	- cd runControl/Xui;              gmake
	- cd runControl/Xui;              gmake install

clean:
	  cd cg;                          gmake clean
	- cd sace3.1;                     gmake clean
	- cd motif;                       gmake clean
	- cd runControl/Xui;              gmake clean
	- cd runControl/rcServer;         gmake clean
